//
//  GrocerySections.swift
//  Gundeti_GroceryApp
//
//  Created by Gundeti,Reshwanth on 4/12/22.
//

import Foundation

struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let groceryitem1 = Grocery(section:"Food",items_Array:[GroceryItem(itemName:"Idli",itemImage:"idli",itemInfo:"The fermentation process breaks down the starches so that they are more readily metabolised by the body. Idli has several variations, including rava idli, which is made from semolina."), GroceryItem(itemName: "Biryani", itemImage: "biryani", itemInfo: "Chicken Biryani is a savory chicken and rice dish that includes layers of chicken, rice, and aromatics that are steamed together. The bottom layer of rice absorbs all the chicken juices as it cooks, giving it a tender texture and rich flavor, while the top layer of rice turns out white and fluffy."), GroceryItem(itemName: "Vada", itemImage: "vada", itemInfo: "Vada or bada is a category of savoury fried snacks from India. Different types of vadas can be described variously as fritters, cutlets, doughnuts, or dumplings. Alternative names for this food include wada, vade, vadai, wadeh and bara."), GroceryItem(itemName: "Upma", itemImage: "upma", itemInfo: "Upma, uppumavu or uppittu is a dish originating from the Indian subcontinent, most common in Andhra Pradesh, Tamil Nadu,Telangana, Karnataka, Maharashtrian and Sri Lankan Tamil breakfast, cooked as a thick porridge from dry-roasted semolina or coarse rice flour."), GroceryItem(itemName: "Shrimp Biryani", itemImage: "shrimp", itemInfo: "Biryani is a delicious dish made by cooking fragrant basmati rice with meat, yogurt, spices & herbs. Chicken biryani & mutton biryani are the much popular versions loved by biryani lovers. Prawn biryani is simply another variation made on the same lines just by replacing chicken & mutton with prawns or shrimps.")] )

let groceryitem2 = Grocery( section: "Pantry", items_Array: [GroceryItem(itemName: "Chocolate Cake", itemImage: "cake", itemInfo: "Chocolate cake is made with chocolate. It can also include other ingredients such as fudge, vanilla creme, and other sweeteners."), GroceryItem(itemName: "Sugar", itemImage: "sugar", itemInfo: "Sugar is a term that includes all sweet carbohydrates, although the term most often is used to describe sucrose or table sugar, a 'double sugar'. The body breaks down carbohydrates into simple sugars such as glucose, that can be readily used in the body. There are several different sugars."), GroceryItem(itemName: "Vegetable Oil", itemImage: "oil", itemInfo: "Vegetable oils, or vegetable fats, are oils extracted from seeds or from other parts of fruits. Like animal fats, vegetable fats are mixtures of triglycerides. Soybean oil, grape seed oil, and cocoa butter are examples of seed oils, or fats from seeds."), GroceryItem(itemName: "Dry Fruits", itemImage: "dryfruits", itemInfo: "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators."), GroceryItem(itemName: "Snacks", itemImage: "snacks", itemInfo: "A snack is a small portion of food generally eaten between meals. Snacks come in a variety of forms including packaged snack foods and other processed foods, as well as items made from fresh ingredients at home.")] )

let groceryitem3 = Grocery( section: "Vegetables", items_Array: [GroceryItem(itemName: "Okra", itemImage: "okra", itemInfo: "Okra or Okro, Abelmoschus esculentus, known in many English-speaking countries as ladies' fingers or ochro, is a flowering plant in the mallow family. Its edible green seed pods are a food. The geographical origin of okra is disputed, with supporters of West African, Ethiopian, and South Asian origins."), GroceryItem(itemName: "Brinjal", itemImage: "brinjal", itemInfo: "Brinjal (Solanum melongena), also known as eggplant or aubergine, is an easily cultivated plant belonging to the family Solanaceae. Its fruit is high in nutrition and commonly consumed as a vegetable. The fruit and other parts of the plant are used in traditional medicine."), GroceryItem(itemName: "Carrot", itemImage: "carrot", itemInfo: "The carrot is a root vegetable, typically orange in color, though purple, black, red, white, and yellow cultivars exist, all of which are domesticated forms of the wild carrot, Daucus carota, native to Europe and Southwestern Asia."), GroceryItem(itemName: "Potatoes", itemImage: "potato", itemInfo: "The potato is a starchy tuber of the plant Solanum tuberosum and is a root vegetable native to the Americas. The plant is a perennial in the nightshade family Solanaceae. Wild potato species can be found throughout the Americas, from Canada to southern Chile."), GroceryItem(itemName: "Cauliflower", itemImage: "cauliflower", itemInfo: "Cauliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the Brassicaceae family. It is an annual plant that reproduces by seed. Typically, only the head is eaten – the edible white flesh sometimes called curd.")] )

let groceryitem4 = Grocery( section: "Cool Drinks", items_Array: [GroceryItem(itemName: "Coca-Cola", itemImage: "coke", itemInfo: "With more than 2,800 products available in more than 200 countries, Coca-Cola is the largest beverage manufacturer and distributor in the world and one of the largest corporations in the United States. Headquarters are in Atlanta, Georgia. Coca-Cola advertisement, c. 1890s."), GroceryItem(itemName: "Sprite", itemImage: "sprite", itemInfo: "Sprite is a colorless, lemon and lime-flavored soft drink created by The Coca-Cola Company. It was first developed in West Germany in 1959 as Fanta Klare Zitrone and was introduced in the United States under the current brand name Sprite in 1961 as a competitor to 7 Up."), GroceryItem(itemName: "ThumsUp", itemImage: "thumsup", itemInfo: "Thums Up is a brand of cola in India. The logo is a red thumbs up. It was introduced in 1977 to offset the withdrawal of The Coca-Cola Company from India. The brand was later bought by Coca-Cola who re-launched it in order to compete against Pepsi."), GroceryItem(itemName: "Lassi", itemImage: "lassi", itemInfo: "Lassi is a regional name for buttermilk, the traditional dahi-based drink in the Indian subcontinent. Lassi is a blend of yogurt, water, spices and sometimes fruit. Namkeen lassi is similar to doogh, while sweet and mango lassis are like milkshakes."), GroceryItem(itemName: "Minute-Maid", itemImage: "minute", itemInfo: "Minute Maid is a product line of beverages that associates with lemonade, orange juice, or soft drinks of many kinds, including Hi-C. the products of the company are orange juices, lemonade and punch juices, light juice drinks, variety juices such as apples and berries, and kids juices and juice drinks.")] )

let groceryitem5 = Grocery( section: "Frozen Food", items_Array: [GroceryItem(itemName: "Chicken", itemImage: "chicken", itemInfo: "Chicken meat contains low collagen levels, which is another positive characteristic. Collagen is a structural protein that reduces meat digestibility, so chicken meat is easier to digest than other types of meat. Chicken meat is also a good source of some minerals and vitamins "), GroceryItem(itemName: "Mutton", itemImage: "mutton", itemInfo: "Mutton refers to the flesh of the mature ram or ewe at least one year old; the meat of sheep between 12 and 20 months old may be called yearling mutton. The meat of sheep 6 to 10 weeks old is usually sold as baby lamb, and spring lamb is from sheep of age five to six months."), GroceryItem(itemName: "Fish", itemImage: "fish", itemInfo: "Fish is the flesh of an animal used for food, and by that definition, it's meat. However, many religions don't consider it meat. There are also several important distinctions between fish and other types of meat, especially in terms of their nutritional profiles and potential health benefits."), GroceryItem(itemName: "Beef", itemImage: "beef", itemInfo: "Beef is the meat of cattle (Bos taurus). It is categorized as red meat — a term used for the meat of mammals, which contains higher amounts of iron than chicken or fish. Usually eaten as roasts, ribs, or steaks, beef is also commonly ground or minced. Patties of ground beef are often used in hamburgers."), GroceryItem(itemName: "Spinach", itemImage: "spinach", itemInfo: "Spinach is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae. Its leaves are a common edible vegetable consumed either fresh, or after storage")] )


let grocerys = [groceryitem1, groceryitem2, groceryitem3, groceryitem4, groceryitem5]


